"""
Dictionaries: road sign categories, linear object categories
"""
road_sign_categories = {
  'UNKNOWN':          0,
  'OTHER':            1,
  'CANCELLATION':     2,
  'INFORMATION_SIGN': 3,
  'LANE_INFORMATION': 4,
  'MANDATORY':        5,
  'NAME':             6,
  'OVERTAKING':       7,
  'OVERTAKING_LANE':  8,
  'POI':              9,
  'PRIORITY':         10,
  'PROHIBITION':      11,
  'RAILWAY_CROSSING': 12,
  'RNR':              13,
  'SIGN_POST':        14,
  'SPEED_RESTRICTION':15,
  'STOP':             16,
  'TOLL_ROAD':        17,
  'TRAFFIC_LIGHTS':   18,
  'VARIABLE':         19,
  'WARNING':          20
}

linear_object_categories = {
  'UNKNOWN':                0,
  'OTHER':                  1,
  'LONG_DASHED_LINE':       2,
  'SHORT_DASHED_LINE':      3,
  'SINGLE_SOLID_LINE':      4,
  'ROAD_BORDER':            5,
  'UNDEFINED_ROAD_BORDER':  6,
  'DOUBLE_SOLID_LINE':      7,
  'SOLID_LINE_DASHED_LINE': 8,
  'DASHED_LINE_SOLID_LINE': 9,
  'SHADED_AREA_MARKING':    10,
  'BARRIER_SOUND':          11,
  'WALL':                   12,
  'CONCRETE_BARRIER':       13,
  'UNKNOWN_BARRIER':        14,
  'DOUBLE_DASHED_LINE':     15,
  'LEFT_CURB':              16,
  'RIGHT_CURB':             17,
  'BI_CURB':                18,
  'FENCE':                  19,
  'DASHED_BLOCKS':          20,
  'CROSSING_ALERT':         21,
  'WALL_TUNNEL':            22,
  'BARRIER_JERSEY':         23,
  'BARRIER_CABLE':          24,
  'BOT_DOTS':               25,
  'GUARDRAIL':              26
}